services:
  - type: web
    name: tecspacs-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    nodeVersion: 20
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 